---
- name: required package | epel-release
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ centos_7_x_required_package }}"
  when: centos_7_x_required_package != []

- name: required package | docker-ce
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ required_package }}"
  when: required_package != []
