---
# required data | <roles_name>
- name: required data | <roles_name>
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data }}"
  when: required_data != []

# required data | template | <roles_name>
- name: required data | template | <roles_name>
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data_template }}"
  when: required_data_template != []
