---
- name: required command | after
  become: True
  become_user: "{{ command_after_become_user if command_after_become_user != '' | default(omit) }}"
  become_method: sudo
  shell: "{{ item.command }}"
  args:
    chdir: "{{ item.chdir | default(omit) }}"
  with_items:
    - "{{ command_after }}"
  when:
    command_after != []
  register: command_after_output

- name: required command output
  debug:
    msg:
      "{{ command_after_output }}"
