---
# required data after | git
- name: required data after | git
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data_after }}"
  when: required_data_after != []

# required data after | template | git
- name: required data after | template | git
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data_template_after }}"
  when: required_data_template_after != []
