---
# update sysctl | git
- name: update sysctl | git
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ sysctl_conf }}"
  when: sysctl_conf != []
