---
- name: required command | before
  become: True
  become_user: "{{ input_user | default('root') }}"
  become_method: sudo
  shell: "{{ item.command }}"
  args:
    chdir: "{{ item.chdir | default('/tmp') }}"
  with_items:
    - "{{ command_before }}"
  when:
    command_before != []
  register: command_before_output

- name: required command output
  debug:
    msg:
      "{{ command_before_output }}"
