---
- name: download repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    accept_hostkey: "{{ item.accept_hostkey | default('yes') }}"
  with_items:
    - "{{ git_repo_remote }}"
  when: git_repo_remote != []
  run_once: true
