---
# set variables | <roles_name>
- name: set variables | <roles_name>
  set_fact:
    roles_name: "{{ role_path|basename }}"
    distribution: "{{ ansible_distribution.lower() }}_{{ ansible_distribution_major_version }}_x"
