---
- name: required package | <roles_name>
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ required_package }}"
  when: required_package != []
