---
# check vars yml exist | docker-ce
- name: check vars yml exist | docker-ce
  local_action: stat path="{{ role_path }}/vars/default_variables.yml"
  register: vars_yml

# include vars yml if exist | docker-ce
- name: reset default variables | docker-ce
  include_vars: "{{ role_path }}/vars/default_variables.yml"
  when: vars_yml.stat.exists == True
    