---
# set variables | docker-ce
- name: set variables | docker-ce
  set_fact:
    roles_name: "{{ role_path|basename }}"
    distribution: "{{ ansible_distribution.lower() }}_{{ ansible_distribution_major_version }}_x"
