---
# update security limit | docker-ce
- name: update security limit | docker-ce
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ security_limit }}"
  when: security_limit != []
