---
# required data after | go
- name: required data after | go
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data_after }}"
  when: required_data_after != []

# required data after | template | go
- name: required data after | template | go
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ required_data_template_after }}"
  when: required_data_template_after != []
