---
# check vars yml exist | go
- name: check vars yml exist | go
  local_action: stat path="{{ role_path }}/vars/default_variables.yml"
  register: vars_yml

# include vars yml if exist | go
- name: reset default variables | go
  include_vars: "{{ role_path }}/vars/default_variables.yml"
  when: vars_yml.stat.exists == True
    